import { createInterface } from "readline";
import { writeFileSync, existsSync, copyFileSync, mkdirSync } from "fs";
import { resolve } from "path";
import { createLogger } from "@vaman-ai/shared";

const log = createLogger("onboard");

function ask(rl: ReturnType<typeof createInterface>, question: string): Promise<string> {
	return new Promise((res) => rl.question(question, (answer) => res(answer.trim())));
}

export async function onboardCommand() {
	const rl = createInterface({ input: process.stdin, output: process.stdout });
	const rootDir = resolve(import.meta.dirname, "../../../..");

	console.log("\nVaman AI - Setup Wizard");
	console.log("======================\n");
	console.log("This wizard will help you configure Vaman AI.\n");

	const env: Record<string, string> = {};

	// --- LLM Provider ---
	console.log("--- LLM Provider ---\n");

	const provider = await ask(rl, "Default provider [openrouter/anthropic/openai/google] (openrouter): ");
	env.DEFAULT_PROVIDER = provider || "openrouter";

	const model = await ask(rl, "Default model (google/gemini-3-flash-preview): ");
	env.DEFAULT_MODEL = model || "google/gemini-3-flash-preview";

	console.log("\nEnter API keys (leave blank to skip):\n");

	const openrouter = await ask(rl, "OPENROUTER_API_KEY: ");
	if (openrouter) env.OPENROUTER_API_KEY = openrouter;

	const anthropic = await ask(rl, "ANTHROPIC_API_KEY: ");
	if (anthropic) env.ANTHROPIC_API_KEY = anthropic;

	const openai = await ask(rl, "OPENAI_API_KEY: ");
	if (openai) env.OPENAI_API_KEY = openai;

	const gemini = await ask(rl, "GEMINI_API_KEY: ");
	if (gemini) env.GEMINI_API_KEY = gemini;

	// --- Discord ---
	console.log("\n--- Discord ---\n");
	const discordToken = await ask(rl, "DISCORD_BOT_TOKEN (leave blank to skip): ");
	if (discordToken) env.DISCORD_BOT_TOKEN = discordToken;

	// --- Gmail ---
	console.log("\n--- Gmail ---\n");
	const gmailAddress = await ask(rl, "Gmail address for Vaman (leave blank to skip): ");
	if (gmailAddress) {
		env.GMAIL_ADDRESS = gmailAddress;

		const credPath = await ask(
			rl,
			"Path to Gmail OAuth credentials JSON (leave blank for default): ",
		);
		if (credPath && existsSync(credPath)) {
			const destDir = resolve(rootDir, "config/credentials");
			mkdirSync(destDir, { recursive: true });
			const dest = resolve(destDir, "gmail-oauth.json");
			copyFileSync(credPath, dest);
			env.GMAIL_CREDENTIALS_PATH = "./config/credentials/gmail-oauth.json";
			console.log(`  Copied credentials to ${dest}`);
		}
	}

	// --- Voice ---
	console.log("\n--- Voice ---\n");
	const pythonPath = await ask(
		rl,
		"Python path with mlx-audio installed (leave blank for python3): ",
	);
	if (pythonPath) env.VOICE_PYTHON_PATH = pythonPath;

	const ttsVoice = await ask(rl, "TTS voice name (af_heart): ");
	if (ttsVoice) env.VOICE_TTS_VOICE = ttsVoice;

	// --- Gateway ---
	console.log("\n--- Gateway ---\n");
	const port = await ask(rl, "Gateway port (18790): ");
	if (port) env.GATEWAY_PORT = port;

	// --- Write .env ---
	const envPath = resolve(rootDir, ".env");
	const lines = Object.entries(env).map(([k, v]) => `${k}=${v}`);
	const envContent = `# Generated by vaman onboard\n${lines.join("\n")}\n`;

	console.log(`\n--- Writing .env to ${envPath} ---\n`);
	console.log(envContent);

	const confirm = await ask(rl, "Write this .env file? (y/n): ");
	if (confirm.toLowerCase() === "y") {
		writeFileSync(envPath, envContent);
		console.log(".env written successfully.");
	} else {
		console.log("Skipped writing .env.");
	}

	// --- LaunchAgent ---
	console.log("\n--- LaunchAgent (auto-start on login) ---\n");
	const installAgent = await ask(rl, "Install macOS LaunchAgent? (y/n): ");
	if (installAgent.toLowerCase() === "y") {
		const plistSrc = resolve(rootDir, "scripts/com.vaman-ai.gateway.plist");
		const plistDest = resolve(
			process.env.HOME || "~",
			"Library/LaunchAgents/com.vaman-ai.gateway.plist",
		);

		if (existsSync(plistSrc)) {
			copyFileSync(plistSrc, plistDest);
			console.log(`LaunchAgent installed to ${plistDest}`);
			console.log("Run: launchctl load ~/Library/LaunchAgents/com.vaman-ai.gateway.plist");
		} else {
			console.log(`LaunchAgent plist not found at ${plistSrc}`);
		}
	}

	console.log("\nSetup complete! Run `vaman chat` to start chatting.\n");
	rl.close();
}
